//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Class()
        {
            this.Student = new HashSet<Student>();
            this.Student1 = new HashSet<Student>();
        }
    
        public int Code { get; set; }
        public string className { get; set; }
        public Nullable<int> codeTeacher { get; set; }
        public Nullable<System.DateTime> Theyear { get; set; }
        public Nullable<int> CodesubstituteTeacher { get; set; }
        public Nullable<bool> IsSubsitute { get; set; }
    
        public virtual Workers Workers { get; set; }
        public virtual Workers Workers1 { get; set; }
        public virtual Workers Workers2 { get; set; }
        public virtual Workers Workers3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Student1 { get; set; }
    }
}
