//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParameterReport
    {
        public int code { get; set; }
        public int codeProfessionType { get; set; }
        public int codeTypeReport { get; set; }
        public int codeParameter { get; set; }
        public int codeCurrentReport { get; set; }
    
        public virtual TypeOfParameterToReport TypeOfParameterToReport { get; set; }
        public virtual typeReport typeReport { get; set; }
    }
}
