//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int codeCaregiver { get; set; }
        public int codeStudent { get; set; }
        public string report1 { get; set; }
        public System.DateTime dateToReport { get; set; }
        public System.DateTime dateReported { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
