//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Report = new HashSet<Report>();
            this.Treatment = new HashSet<Treatment>();
            this.Treatment1 = new HashSet<Treatment>();
        }
    
        public int code { get; set; }
        public string studentName { get; set; }
        public string lastName { get; set; }
        public Nullable<int> codeClass { get; set; }
        public Nullable<System.DateTime> birthDate { get; set; }
        public string fatherName { get; set; }
        public string motherName { get; set; }
        public string phone { get; set; }
        public string celPhone1 { get; set; }
        public string celPhone2 { get; set; }
        public string id { get; set; }
        public Nullable<int> codeCity { get; set; }
    
        public virtual City City { get; set; }
        public virtual City City1 { get; set; }
        public virtual Class Class { get; set; }
        public virtual Class Class1 { get; set; }
        public virtual PersonalFile PersonalFile { get; set; }
        public virtual PersonalFile PersonalFile1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report> Report { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Treatment> Treatment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Treatment> Treatment1 { get; set; }
    }
}
