//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treatment
    {
        public int Code { get; set; }
        public Nullable<int> codeCaregiver { get; set; }
        public Nullable<int> codeStudent { get; set; }
        public string treatmentDescription { get; set; }
        public Nullable<int> grade { get; set; }
        public Nullable<System.DateTime> treatmentDate { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Student Student1 { get; set; }
        public virtual Workers Workers { get; set; }
        public virtual Workers Workers1 { get; set; }
    }
}
